spoticharts/urls.py
from django.urls import path
from . import views
app_name = 'spoticharts'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('charts', views.charts, name='charts'),
]

spotihtml/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spoticharts/', include('spoticharts.urls')),
]

spoticharts/models.py
from django.db import models

# Create your models here.

spoticharts/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'spoticharts/index.html')

def about(request):
    return render(request, 'spoticharts/about.html')

def charts(request):
    return render(request, 'spoticharts/charts.html')

spoticharts/templates/spoticharts/about.html
{% extends 'spoticharts/layout.html' %}
{% block body %}
{% load static %}
<h1 id="centerHeader">Meet the ✨panes✨ team</h1>
<h2 id="centerH2">Our team is conformed by three awesome people 💋</h2>
<section id="members">
<div class="member">
    <img src="{% static 'spoticharts/alan.png' %}" alt="A drawing of Alan">
    <h1>Alan Florez</h1>
    <p>Crazy guy</p>
</div>
<div class="member">
    <img src="{% static 'spoticharts/tabata.png' %}" alt="A drawing of Tabata">
    <h1>Tabata Llach</h1>
    <p>Back-End Developer</p>
</div>
<div class="member">
    <img src="{% static 'spoticharts/katy.png' %}" alt="A drawing of Katy">
    <h1>Katy Diaz</h1>
    <p>Front-End Developer</p>
</div>
</section>
{% endblock %}

spoticharts/templates/spoticharts/charts.html
{% extends 'spoticharts/layout.html' %}

spoticharts/templates/spoticharts/index.html
{% extends 'spoticharts/layout.html' %}
{% block body %}
    <h2>Hi, this is Spoticharts 👋</h2>
    <h1>Let's give a try to our page, we have many options to explore</h1>
    <div class="line"></div>
    <section id="details">
        <div>
            <h2>What Spoticharts does</h2>
        <p>Spoticharts is a website that is customized according to your musical tastes,
            allows you to discover related music and offers you the possibility to compare
            the popularity of songs and playlists over time, giving you a more complete and
            enriching music experience.</p>
            <a href="https://www.kaggle.com/datasets/dhruvildave/spotify-charts">Our DataFrame ></a>
        </div>
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
        <lottie-player src="https://assets2.lottiefiles.com/private_files/lf30_fjln45y5.json" background="transparent"  speed="1" loop autoplay></lottie-player>
    </section>
{% endblock %}

spoticharts/templates/spoticharts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Spoticharts</title>
    <link rel="stylesheet" href="{% static 'spoticharts/styles.css'%}">
</head>
<body>
    <header>
        <nav class="navbar">
            <a href="{% url 'spoticharts:index' %}">🏠Home</a>
            <a href="{% url 'spoticharts:charts' %}">🔎Compare</a>
            <a href="{% url 'spoticharts:about' %}">📧About</a>
        </nav>
    </header>
    {% block body %}
    {% endblock %}
</body>
</html>